management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

spring:
  jpa:
    generate-ddl: true

#  cloud:
#    config:
#      uri: "http://helix.config.server/:8888"
#      token: "MyTokenGoesHere"
#      name: "MyApplicationName"
